/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by @tanstack/router-vite-plugin.
// Run `vite dev` to regenerate with your actual routes.

import { createRootRoute, createRoute, createRouter } from '@tanstack/react-router'

import { Route as rootRoute }        from './routes/__root'
import { Route as IndexImport }      from './routes/index'
import { Route as LoginImport }      from './routes/login'
import { Route as RegisterImport }   from './routes/register'
import { Route as LockImport }       from './routes/lock'
import { Route as HomeImport }       from './routes/home'
import { Route as SettingsImport }   from './routes/settings'
import { Route as ThemeStudioImport }from './routes/theme-studio'
/*@if:widgets*/
import { Route as WidgetsImport }    from './routes/widgets'
/*@endif:widgets*/

const IndexRoute       = IndexImport.update({ path: '/',             getParentRoute: () => rootRoute } as any)
const LoginRoute       = LoginImport.update({ path: '/login',        getParentRoute: () => rootRoute } as any)
const RegisterRoute    = RegisterImport.update({ path: '/register',  getParentRoute: () => rootRoute } as any)
const LockRoute        = LockImport.update({ path: '/lock',          getParentRoute: () => rootRoute } as any)
const HomeRoute        = HomeImport.update({ path: '/home',          getParentRoute: () => rootRoute } as any)
const SettingsRoute    = SettingsImport.update({ path: '/settings',  getParentRoute: () => rootRoute } as any)
const ThemeStudioRoute = ThemeStudioImport.update({ path: '/theme-studio', getParentRoute: () => rootRoute } as any)
/*@if:widgets*/
const WidgetsRoute     = WidgetsImport.update({ path: '/widgets',    getParentRoute: () => rootRoute } as any)
/*@endif:widgets*/

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/'            : { id: '/';             path: '/';             fullPath: '/'             }
        '/login'       : { id: '/login';        path: '/login';        fullPath: '/login'        }
        '/register'    : { id: '/register';     path: '/register';     fullPath: '/register'     }
        '/lock'        : { id: '/lock';         path: '/lock';         fullPath: '/lock'         }
        '/home'        : { id: '/home';         path: '/home';         fullPath: '/home'         }
        '/settings'    : { id: '/settings';     path: '/settings';     fullPath: '/settings'     }
        '/theme-studio': { id: '/theme-studio'; path: '/theme-studio'; fullPath: '/theme-studio' }
        /*@if:widgets*/
        '/widgets'     : { id: '/widgets';      path: '/widgets';      fullPath: '/widgets'      }
        /*@endif:widgets*/
    }
}

export const routeTree = rootRoute._addFileChildren([
    IndexRoute, LoginRoute, RegisterRoute, LockRoute,
    HomeRoute, SettingsRoute, ThemeStudioRoute,
    /*@if:widgets*/
    WidgetsRoute,
    /*@endif:widgets*/
])
